### ISSUE TITLE
multi-platform builds

### ISSUE THREAD

**Issue by ltalirz** [conda-forge/nwchem-feedstock#1]
- [x] macos
- [ ] [on hold] windows

**Comment by edoapra** [comment]
A native windows build is more or less hopeless. Better use WSL (or virtual machines/containers) on Windows 10

**Comment by ltalirz** [comment]
Thanks, I just added it because I saw "win64" among the binaries https://github.com/nwchemgit/nwchem/releases/tag/v7.0.2-release

conda-forge uses the microsoft visual studio compilers - if it's not worth the try we can put that one on hold

**Comment by edoapra** [comment]
Never tried the  microsoft visual studio compilers. The inefficient and kludgy windows port of NWChem uses MinGW

**Comment by ltalirz** [comment]
MacOS build added in https://github.com/conda-forge/nwchem-feedstock/pull/7
Windows build postponed.

**Comment by ltalirz** [comment]
> Never tried the microsoft visual studio compilers. The inefficient and kludgy windows port of NWChem uses MinGW

Out of curiosity: does the windows build use scalapack? If yes, which MPI library does this use?

I just came across this question in another package - conda-forge has no windows builds for openmpi and mpich. In principle, there is the [msmpi](https://anaconda.org/conda-forge/msmpi) but [scalapack](https://anaconda.org/conda-forge/scalapack) does not seem to support it (at least the conda package has no windows build).

By the way, are there other features (e.g. enabled by additional libraries) that should be enabled in the nwchem feedstock or can it be considered somewhat feature-complete?

**Comment by edoapra** [comment]
I am sorry to tell you that I don't see any point in wasting more of my time on Windows builds.
All the effort I put in the mingw build resulted in performance lower than the WSL or Docker builds.
The mingw build does use msmpi.
If you want to look into this, I wish good luck but I am not going to be of any help.

**Comment by ltalirz** [comment]
Thanks, that's great to know! 
I'll keep this experience in mind, also for other packages.
