### ISSUE TITLE
speed up build

### ISSUE THREAD

**Issue by ltalirz** [conda-forge/nwchem-feedstock#2]
As discussed [here](https://github.com/conda-forge/staged-recipes/pull/14725#issuecomment-837373539) the feedstock currently builds a separate executable for each python version (3.5, 3.6, 3.7, 3.8, 3.9) because the nwchem python interface may require this.
This makes the builds very long (>5h).

 1. It is not entirely clear whether this is necessary (see [here](https://github.com/nwchemgit/nwchem/tree/master/src/python) , I think it might be)
 2. In either case it might make sense to split the python interface into a separate package that *depends* on `nwchem`. A user of the python interface would then simply `conda install -c conda-forge nwchempy` (name to be decided) and get `nwchem` shipped automatically.

Perhaps @edoapra could comment on whether he sees a straightforward way of building the python interface, starting from what is present in the `nwchem` package.

**Comment by edoapra** [comment]
If you want to build NWChem without Python, simply set
```
NWCHEM_MODULES=all
```
Instead, `nwchempy` would require
```
NWCHEM_MODULES="all python"
```

**Comment by ltalirz** [comment]
> Instead, `nwchempy` would require
> 
> ```
> NWCHEM_MODULES="all python"
> ```

Thanks! Ideally I was hoping we could reuse the already built `nwchem` package and just build the python interface on top of it.
Looking at the [docs](https://nwchemgit.github.io/Python.html) for the nwchem python interface, however, the nwchem python interface seems to be a bit peculiar in that the python code is fed to the nwchem binary as input.

Do I understand correctly that the `libnwpython.a` is linked into the `nwchem` executable directly, and that it is not straightforward to create a "python-enabled" `nwchem` from a "not-python-enabled" `nwchem`?

**Comment by edoapra** [comment]
The only was to create a "python-enabled" nwchem from a "not-python-enabled" nwchem is to re-link
```
cd $NWCHEM_TOP/src
make nwchem_config NWCHEM_MODULES="all"
make 
```
This creates `nwchem` without python.
Instead, the following created nwchem without python from an existing compilation of NWChem without python
```
cd $NWCHEM_TOP/src
make nwchem_config NWCHEM_MODULES="all python"
cd python; make
cd ..
make link
```
If you need to created "python-enabled" nwchem with different Python settings, you would simply have to repeat the procedure above with minor tweaks to pass the Python settings
```
cd $NWCHEM_TOP/src
make nwchem_config NWCHEM_MODULES="all python"
```
define python settings
```
cd python; make clean;  make
cd ..
make link
```

**Comment by ltalirz** [comment]
Thanks for the clear instructions!

The problem is that the builds for the different python versions happen in separate containers, i.e. there is no way for me to e.g. use one container to build all of them (I believe).

I guess for the moment we will need to live with the separate full builds for each python version... on the feedstock at least they run in parallel so they don't hold up debugging (of course it's quite a waste of CPU resources...)
