### ISSUE TITLE
Basis set library definition

### ISSUE THREAD

**Issue by edoapra** [conda-forge/nwchem-feedstock#6]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:  
After install NWChem with  the command
```
conda install  nwchem
```
any attempts to use the builtin basis library files fails with the error
```
  warning:::::::::::::: from_compile
  NWCHEM_BASIS_LIBRARY is: </home/conda/feedstock_root/build_artifacts/nwchem_1621071858803/work/src/basis/libraries/>
  but file does not exist or you do not have access to it !
 Attempting to read a basis set from a  non-existing file:
 /home/conda/feedstock_root/build_artifacts/nwchem_1621071858803/work/src/basis/libraries/cc-pvdz     
```
There are two ways for the user to fix this problem
* set the environment variable `NWCHEM_BASIS_LIBRARY` to the installation directories
```
export NWCHEM_BASIS_LIBRARY=$CONDA_PREFIX//data/edo/condas/minconda3/share/nwchem/libraries/
```
* copy the file `.nwchemrc` to the `$HOME` directory
```
cp $CONDA_PREFIX/etc/default.nwchemrc $HOME/.nwchemrc
```

The preferred way is option no. 1 and it could be loaded in the user's environment while the command `conda install nwchem` is executed.   
Option no. 2 could be mentioned at the end of the installation (in similar fashion to the OpenMPI warnings), since it is needed when using Classical MD 

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /data/edo/condas/minconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
brotlipy                  0.7.0           py39h3811e60_1001    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py39hf3d152e_1    conda-forge
cffi                      1.14.5           py39he32792d_0    conda-forge
chardet                   4.0.0            py39hf3d152e_1    conda-forge
conda                     4.10.1           py39hf3d152e_0    conda-forge
conda-package-handling    1.7.3            py39h3811e60_0    conda-forge
cryptography              3.4.7            py39hbca0aa6_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_0    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
mpi                       1.0                     openmpi    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nwchem                    7.0.2            py39hea0d9f8_0    conda-forge
openblas                  0.3.15          pthreads_h4748800_0    conda-forge
openmpi                   4.1.1                hbfc84c5_0    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pip                       21.1.1             pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py39h3811e60_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39hf3d152e_3    conda-forge
python                    3.9.4           hffdb5ce_0_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
ruamel_yaml               0.15.80         py39h3811e60_1004    conda-forge
scalapack                 2.0.2             hc7fdd6d_1009    conda-forge
setuptools                49.6.0           py39hf3d152e_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : base
    active env location : /data/edo/condas/minconda3
            shell level : 1
       user config file : /home/edo/.condarc
 populated config files : /home/edo/.condarc
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.9.4.final.0
       virtual packages : __cuda=11.3=0
                          __linux=5.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /data/edo/condas/minconda3  (writable)
      conda av data dir : /data/edo/condas/minconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /data/edo/condas/minconda3/pkgs
                          /home/edo/.conda/pkgs
       envs directories : /data/edo/condas/minconda3/envs
                          /home/edo/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.9.4 Linux/5.4.0-72-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


```
</details>

**Comment by ltalirz** [comment]
Thanks a lot for checking @edoapra !

I would need to check how to notify users about this - however, I'm wondering whether there might be a better way: is it possible to hardcode a relative path for `NWCHEM_BASIS_LIBRARY` into the `nwchem` binary?
That's what conda does with the `rpath` for linking dynamic libraries (which are thus automatically picked from the right environment).

If it helps, we could even create a symlink during the compile stage that puts the basis library at the same relative location as it will be in the final install.

Edit: Ah hm... if `NWCHEM_BASIS_LIBRARY` is looked up from the current working directory rather than from the location of the binary (even for the hardcoded one), then I guess there is no way around notifying the user...

**Comment by edoapra** [comment]
> I would need to check how to notify users about this - however, I'm wondering whether there might be a better way: is it possible to hardcode a relative path for `NWCHEM_BASIS_LIBRARY` into the `nwchem` binary?

No, this option is not available yet

**Comment by ltalirz** [comment]
Hey @edoapra -  looking back at this, I believe this should already be taken care of by the activate scripts.
E.g. 

```
$ cat  /home/ubuntu/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64/envs/nwchem/etc/conda/activate.d/nwchem_env.sh
if [ ! -f $HOME/.nwchemrc ]; then
    ln -s $CONDA_PREFIX/etc/default.nwchemrc $HOME/.nwchemrc
	touch $HOME/.CONDANWCHEMRC
fi
$ cat ~/.nwchemrc
nwchem_basis_library /home/ubuntu/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64/envs/nwchem/share/nwchem/libraries/
nwchem_nwpw_library /home/ubuntu/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64/envs/nwchem/share/nwchem/libraryps/
ffield amber
amber_1 /home/ubuntu/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64/envs/nwchem/share/nwchem/data/amber_s/
amber_2 /home/ubuntu/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64/envs/nwchem/share/nwchem/data/amber_q/
amber_3 /home/ubuntu/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64/envs/nwchem/share/nwchem/data/amber_x/
amber_4 /home/ubuntu/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64/envs/nwchem/share/nwchem/data/amber_u/
spce /home/ubuntu/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64/envs/nwchem/share/nwchem/data/solvents/spce.rst
charmm_s /home/ubuntu/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64/envs/nwchem/share/nwchem/data/charmm_s/
charmm_x /home/ubuntu/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64/envs/nwchem/share/nwchem/data/charmm_x/
```

The thing is that I believe this will only happen the next time you activate the environment, i.e. it won't be available immediately after you install nwchem.

Can you confirm?

**Comment by edoapra** [comment]
Those changes are likely to work.
However, there are users (like me) that prefer to use the env. variable `NWCHEM_BASIS_LIBRARY`, instead.

**Comment by ltalirz** [comment]
> Those changes are likely to work.

Not sure whether I was clear: this is already done by the current version of the nwchem conda package (see [build script section](https://github.com/conda-forge/nwchem-feedstock/blob/165e7a34e05311392b6621b23feed1ee719c90c2/recipe/build.sh#L74-L105)).

> However, there are users (like me) that prefer to use the env. variable `NWCHEM_BASIS_LIBRARY`, instead.

I see. Should we disable the corresponding section in the build script?
In any case I can look into how to get messages to appear after installation

**Comment by edoapra** [comment]
> > Those changes are likely to work.
> 
> Not sure whether I was clear: this is already done by the current version of the nwchem conda package (see [build script section](https://github.com/conda-forge/nwchem-feedstock/blob/165e7a34e05311392b6621b23feed1ee719c90c2/recipe/build.sh#L74-L105)).
> 

Sure, the current `default.nwchemrc` does work after it has been copied to `$HOME/.nwchemrc`
```
cp $CONDA_PREFIX/etc/default.nwchemrc $HOME/.nwchemrc
```
My suggestion would be to suggest to the user this copy operation at the end of the execution of the `conda install nwchem` command

**Comment by edoapra** [comment]
> > However, there are users (like me) that prefer to use the env. variable `NWCHEM_BASIS_LIBRARY`, instead.
> 
> I see. Should we disable the corresponding section in the build script?
> In any case I can look into how to get messages to appear after installation

Where is the corresponding section  in the build script?

**Comment by ltalirz** [comment]
> Where is the corresponding section in the build script?

Sorry, I meant the one linked above: [build script section](https://github.com/conda-forge/nwchem-feedstock/blob/165e7a34e05311392b6621b23feed1ee719c90c2/recipe/build.sh#L74-L105)

We could get rid of this in favor of some explanatory notes after installing nwchem

**Comment by edoapra** [comment]
I have just tested`nwchemrc` option on MacOS. It's working, but there are still a few glitches.
* If `$HOME/.nwchemrc` does not exist prior to `conda install nwchem`, I am getting the error
```
rm: /Users/edo/.nwchemrc: No such file or directory
```
Is this due to this line in `$CONDA_PREFIX//etc/conda/deactivate.d/nwchem_env.sh` ?
```
    rm $HOME/.CONDANWCHEMRC $HOME/.nwchemrc
```
Should it be `rm -f ` instead of `rm` ?

* After the command `conda uninstall nwchem`, `$HOME/.nwchemrc` still exist as a symbolic link to a file removed by the `uninstall` command
```
$HOME/.nwchemrc -> $CONDA_PREFIX/etc/default.nwchemrc
```

**Comment by edoapra** [comment]
As I have already mentioned, I would rather have the `NWCHEM_BASIS_LIBRARY` option in place.
Could we add the following lines to `$PREFIX/etc/conda/activate.d/nwchem_env.sh`  ?
```
export NWCHEM_BASIS_LIBRARY=$PREFIX/share/nwchem/libraries/
export NWCHEM_NWPW_LIBRARY=$PREFIX/share/nwchem/libraryps/

**Comment by ltalirz** [comment]
How about this:

 1. We get rid of the automatic addition of the `~/.nwchemrc` entirely (I also prefer not to pollute the user's home directory; this was copied from the nwchem conda recipe that I used as a starting point)
 2. We add a `$PREFIX/etc/conda/activate.d/nwchem_env.sh` that simply contains the two `export` statements you mention above, nothing else

Would that address all issues?

E.g. I don't know whether these things also have corresponding environment variables that we may want to set?
```
ffield amber
amber_1 $PREFIX/share/nwchem/data/amber_s/
amber_2 $PREFIX/share/nwchem/data/amber_q/
amber_3 $PREFIX/share/nwchem/data/amber_x/
amber_4 $PREFIX/share/nwchem/data/amber_u/
spce $PREFIX/share/nwchem/data/solvents/spce.rst
charmm_s $PREFIX/share/nwchem/data/charmm_s/
charmm_x $PREFIX/share/nwchem/data/charmm_x/
```

**Comment by edoapra** [comment]
The Classical MD definitions are only possible via `.nwchemrc`
My suggestions is to
* use the two `export` statements in `nwchem_env.sh`
*  generate a new script (e.g. `donwchemrc.sh`) that generates the `.nwchemrc` mechanism. `donwchemrc.sh` is not executed by default, but it is left to the user to activate it. We could mention  this option  at the end of the output of the `conda install nwchem` command or add a new option (`y/n execute donwchemrc.sh`)
